export interface CharacterCardDefinition {
  definitionId: string;
  displayName: string;
  printedATK: number;
  printedDEF: number;
  ability: string | null;
  statRule: string | null;
  imageKey: string;
}

// Approved Alpha 1 pool, exactly once each.
export const ALPHA_1_CHARACTER_DEFINITIONS: CharacterCardDefinition[] = [
  {
    definitionId: 'alpha-001',
    displayName: 'BRENDAN',
    printedATK: 5,
    printedDEF: 4,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-001',
  },
  {
    definitionId: 'alpha-002',
    displayName: 'LUKE',
    printedATK: 4,
    printedDEF: 3,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-002',
  },
  {
    definitionId: 'alpha-003',
    displayName: 'JOHN CENA',
    printedATK: 6,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-003',
  },
  {
    definitionId: 'alpha-004',
    displayName: 'BATMAN',
    printedATK: 7,
    printedDEF: 6,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-004',
  },
  {
    definitionId: 'alpha-005',
    displayName: 'BAXTER',
    printedATK: 6,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-005',
  },
  {
    definitionId: 'alpha-006',
    displayName: 'SPIDER-MAN',
    printedATK: 7,
    printedDEF: 8,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-006',
  },
  {
    definitionId: 'alpha-007',
    displayName: 'KEITH',
    printedATK: 8,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-007',
  },
  {
    definitionId: 'alpha-008',
    displayName: 'HULK',
    printedATK: 8,
    printedDEF: 8,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-008',
  },
  {
    definitionId: 'alpha-009',
    displayName: 'RICK GRIMES',
    printedATK: 9,
    printedDEF: 8,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-009',
  },
  {
    definitionId: 'alpha-010',
    displayName: 'DARYL DIXON',
    printedATK: 7,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-010',
  },
  {
    definitionId: 'alpha-011',
    displayName: 'NEBULA',
    printedATK: 7,
    printedDEF: 6,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-011',
  },
  {
    definitionId: 'alpha-012',
    displayName: 'GAMORA',
    printedATK: 8,
    printedDEF: 7.5,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-012',
  },
  {
    definitionId: 'alpha-013',
    displayName: 'LARRY',
    printedATK: 8,
    printedDEF: 7.5,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-013',
  },
  {
    definitionId: 'alpha-014',
    displayName: 'PATRICK',
    printedATK: 6,
    printedDEF: 9,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-014',
  },
  {
    definitionId: 'alpha-015',
    displayName: 'SANDY CHEEKS',
    printedATK: 9,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-015',
  },
  {
    definitionId: 'alpha-016',
    displayName: 'TOPH',
    printedATK: 9,
    printedDEF: 9,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-016',
  },
  {
    definitionId: 'alpha-017',
    displayName: 'CEDI OSMAN',
    printedATK: 6,
    printedDEF: 5,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-017',
  },
  {
    definitionId: 'alpha-018',
    displayName: 'LEGO CAP / CAPTAIN AMERICA',
    printedATK: 3,
    printedDEF: 2,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-018',
  },
  {
    definitionId: 'alpha-019',
    displayName: 'THE PENGUIN',
    printedATK: 2,
    printedDEF: 9,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-019',
  },
  {
    definitionId: 'alpha-020',
    displayName: 'MR. FREEZE',
    printedATK: 9,
    printedDEF: 9,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-020',
  },
  {
    definitionId: 'alpha-021',
    displayName: 'BOB',
    printedATK: 10,
    printedDEF: 10,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-021',
  },
  {
    definitionId: 'alpha-022',
    displayName: 'SOKKA',
    printedATK: 6,
    printedDEF: 5,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-022',
  },
  {
    definitionId: 'alpha-023',
    displayName: 'ZUKO',
    printedATK: 8,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-023',
  },
  {
    definitionId: 'alpha-024',
    displayName: 'GENGHIS KHAN',
    printedATK: 8,
    printedDEF: 8,
    ability: 'If Mongol Empire is used on Genghis Khan, the +5 ATK becomes permanent.',
    statRule: null,
    imageKey: 'placeholder-alpha-024',
  },
  {
    definitionId: 'alpha-025',
    displayName: 'KOOL-AID MAN',
    printedATK: 10,
    printedDEF: 1,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-025',
  },
  {
    definitionId: 'alpha-026',
    displayName: 'ROOMBA',
    printedATK: 5,
    printedDEF: 6,
    ability: 'After Roomba is revealed, its player draws 1 Power Card every time Roomba moves.',
    statRule: null,
    imageKey: 'placeholder-alpha-026',
  },
  {
    definitionId: 'alpha-027',
    displayName: 'NIGHTCRAWLER',
    printedATK: 6.5,
    printedDEF: 7,
    ability: 'Instead of moving normally, Nightcrawler may teleport up to 3 spaces forward or backward to an open spot.',
    statRule: null,
    imageKey: 'placeholder-alpha-027',
  },
  {
    definitionId: 'alpha-028',
    displayName: 'RAPUNZEL',
    printedATK: 5,
    printedDEF: 7,
    ability: 'Once per game after Rapunzel is revealed, pull the first character behind her to the open spot directly in front of her.',
    statRule: null,
    imageKey: 'placeholder-alpha-028',
  },
  {
    definitionId: 'alpha-029',
    displayName: 'MRS. PUFF',
    printedATK: 1,
    printedDEF: 10,
    ability: 'Once per game after Mrs. Puff is revealed, she may puff up. Move the character directly in front of her to the next open spot forward, and the character directly behind her to the next open spot backward, if possible.',
    statRule: null,
    imageKey: 'placeholder-alpha-029',
  },
  {
    definitionId: 'alpha-030',
    displayName: 'SPONGEBOB',
    printedATK: 4,
    printedDEF: 8,
    ability: 'SpongeBob automatically defeats Mrs. Puff.',
    statRule: null,
    imageKey: 'placeholder-alpha-030',
  },
  {
    definitionId: 'alpha-031',
    displayName: 'ANT',
    printedATK: 1,
    printedDEF: 1,
    ability: 'If Ant wins any battle, draw 2 Power Cards.',
    statRule: null,
    imageKey: 'placeholder-alpha-031',
  },
  {
    definitionId: 'alpha-032',
    displayName: 'CARL GRIMES',
    printedATK: 5.5,
    printedDEF: 5,
    ability: 'If Rick is alive, Rick and Carl get +2 ATK / +2 DEF.',
    statRule: null,
    imageKey: 'placeholder-alpha-032',
  },
  {
    definitionId: 'alpha-033',
    displayName: 'RIDDLER',
    printedATK: 0,
    printedDEF: 0,
    ability: null,
    statRule: 'When Riddler is revealed for battle, reveal the bottom Character Card of the deck and use that card\'s ATK and DEF for this battle. After battle, that revealed bottom card goes to Graveyard.',
    imageKey: 'placeholder-alpha-033',
  },
  {
    definitionId: 'alpha-034',
    displayName: 'UNCLE IROH',
    printedATK: 9,
    printedDEF: 7,
    ability: 'Once per game after Iroh is revealed, cancel one opponent\'s Power Card.',
    statRule: null,
    imageKey: 'placeholder-alpha-034',
  },
  {
    definitionId: 'alpha-035',
    displayName: 'JEREMY JAHNS',
    printedATK: 6,
    printedDEF: 6.5,
    ability: 'Once per game after Jeremy is revealed, look at the top 3 Power Cards. Keep 1 and put the others back in any order.',
    statRule: null,
    imageKey: 'placeholder-alpha-035',
  },
  {
    definitionId: 'alpha-036',
    displayName: 'SKAR PRODUCTIONS',
    printedATK: 7.5,
    printedDEF: 6,
    ability: 'Once per game after a battle involving Skar, take one Power Card played during that battle and add it to your hand.',
    statRule: null,
    imageKey: 'placeholder-alpha-036',
  },
  {
    definitionId: 'alpha-037',
    displayName: 'BIRD',
    printedATK: 2,
    printedDEF: 2,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-037',
  },
  {
    definitionId: 'alpha-038',
    displayName: 'AVATAR AANG',
    printedATK: 8.5,
    printedDEF: 8.5,
    ability: 'Once per game, if Aang loses a battle, move him to an open spot directly behind him or behind his opponent instead of dying. Then Aang permanently loses -1 ATK and -1 DEF.',
    statRule: null,
    imageKey: 'placeholder-alpha-038',
  },
];
