export interface CharacterCardDefinition {
  definitionId: string;
  displayName: string;
  printedATK: number;
  printedDEF: number;
  ability: string | null;
  statRule: string | null;
  imageKey: string;
}

// Approved Alpha 1 pool, exactly once each.
export const ALPHA_1_CHARACTER_DEFINITIONS: CharacterCardDefinition[] = [
  {
    definitionId: 'alpha-001',
    displayName: 'BRENDAN',
    printedATK: 5,
    printedDEF: 4,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-001',
  },
  {
    definitionId: 'alpha-002',
    displayName: 'LUKE',
    printedATK: 4,
    printedDEF: 3,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-002',
  },
  {
    definitionId: 'alpha-003',
    displayName: 'JOHN CENA',
    printedATK: 6,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-003',
  },
  {
    definitionId: 'alpha-004',
    displayName: 'BATMAN',
    printedATK: 7,
    printedDEF: 6,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-004',
  },
  {
    definitionId: 'alpha-005',
    displayName: 'BAXTER',
    printedATK: 6,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-005',
  },
  {
    definitionId: 'alpha-006',
    displayName: 'SPIDER-MAN',
    printedATK: 7,
    printedDEF: 8,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-006',
  },
  {
    definitionId: 'alpha-007',
    displayName: 'KEITH',
    printedATK: 8,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-007',
  },
  {
    definitionId: 'alpha-008',
    displayName: 'HULK',
    printedATK: 8,
    printedDEF: 8,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-008',
  },
  {
    definitionId: 'alpha-009',
    displayName: 'RICK GRIMES',
    printedATK: 9,
    printedDEF: 8,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-009',
  },
  {
    definitionId: 'alpha-010',
    displayName: 'DARYL DIXON',
    printedATK: 7,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-010',
  },
  {
    definitionId: 'alpha-011',
    displayName: 'NEBULA',
    printedATK: 7,
    printedDEF: 6,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-011',
  },
  {
    definitionId: 'alpha-012',
    displayName: 'GAMORA',
    printedATK: 8,
    printedDEF: 7.5,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-012',
  },
  {
    definitionId: 'alpha-013',
    displayName: 'LARRY',
    printedATK: 8,
    printedDEF: 7.5,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-013',
  },
  {
    definitionId: 'alpha-014',
    displayName: 'PATRICK',
    printedATK: 6,
    printedDEF: 9,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-014',
  },
  {
    definitionId: 'alpha-015',
    displayName: 'SANDY CHEEKS',
    printedATK: 9,
    printedDEF: 7,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-015',
  },
  {
    definitionId: 'alpha-016',
    displayName: 'TOPH',
    printedATK: 9,
    printedDEF: 9,
    ability: null,
    statRule: null,
    imageKey: 'placeholder-alpha-016',
  },
];
